name: All_Security_Scan_Upload

on:
  workflow_dispatch:   # manual trigger also supported

# ---- Global environment variables (shared across all jobs) ----
env:
  DEFECTDOJO_URL: "https://demo.defectdojo.org/api/v2/import-scan/"
  ENGAGEMENT_NAME: "DAST_pipeline"
  PRODUCT_TYPE_NAME: "Research and Development"
  PRODUCT_NAME: "WebApp"
  REPORTS_DIR: reports
  System_Debug: true

jobs:
  # ---------- INIT ----------
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment Info
        run: |
          echo "PATH=$PATH"
          echo "M2_HOME=$M2_HOME"
          pwd
          ls -al

  # ---------- BUILD ----------
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  # ---------- SECURITY SCANS ----------
  security_scans:
    runs-on: ubuntu-latest
    needs: build
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
      TARGET_URL: ${{ github.event.inputs.TARGET_URL || 'http://testphp.vulnweb.com' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---- Secret Scan (Trufflehog) ----
      - name: Trufflehog Scan
        run: |
          mkdir -p $REPORTS_DIR/trufflehog
          docker run --rm gesellix/trufflehog --json https://github.com/jdpatilonline/Webapp-DevSecops.git > $REPORTS_DIR/trufflehog/trufflehog.json || true
          ls -alR $REPORTS_DIR

      # ---- Secret Scan (GitGuardian) ----
      - name: GitGuardian Scan
        run: |
          mkdir -p $REPORTS_DIR/GitGuardian
          pip install ggshield
          ggshield api-status
          ggshield secret scan ci || true
          ggshield secret scan ci --json > $REPORTS_DIR/GitGuardian/ggshield-report.json || true
          cat $REPORTS_DIR/GitGuardian/ggshield-report.json || true
          ls -alR $REPORTS_DIR
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

      # ---- SCA (Trivy) ----
      - name: Trivy Scan
        run: |
          mkdir -p $REPORTS_DIR/trivy
          docker run --rm -u 0 -v $(pwd):/scan -v $(pwd)/$REPORTS_DIR/trivy:/report aquasec/trivy fs /scan --format json --output /report/trivy-fs-report.json || true
          #docker run --rm -u 0 -v $(pwd):/scan -v $(pwd)/$REPORTS_DIR/trivy:/report aquasec/trivy image --format json --output #/report/trivy-fs-report.json vulnerables/web-dvwa || true
          ls -alR $REPORTS_DIR

      # ---- SAST (Semgrep) ----
      - name: Semgrep Scan
        run: |
          mkdir -p $REPORTS_DIR/semgrep
          docker run --rm -v "$PWD:/src" semgrep/semgrep semgrep scan --config=auto --json --output $REPORTS_DIR/semgrep/semgrep-report.json || true
          ls -alR $REPORTS_DIR

      # ---- SCA (Snyk) ----
      - name: Snyk Scan
        run: |
          mkdir -p $REPORTS_DIR/Snyk
          npm install -g snyk
          snyk auth $SNYK_TOKEN
          snyk code test --all-projects --json-file-output=$REPORTS_DIR/Snyk/snyk-sca.json || true
          snyk code test || true
          snyk monitor --all-projects || true
          snyk container monitor vulnerables/web-dvwa || true
          ls -alR $REPORTS_DIR

      # SonarCloud scan (ALL properties inline)
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #auto‑provided by GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=jdpatilonline
            -Dsonar.projectKey=jdpatilonline_DevSecOps_GitAction
            -Dsonar.projectName=DevSecOps_GitAction
            -Dsonar.sources=.
            -Dsonar.exclusions=**/tests/**,**/docs/**,**/vendor/**,**/*.md
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.qualitygate.wait=false
            -Dsonar.qualitygate.timeout=300

      - name: Fetch Soanr CloudQuality Gate Status
        run: |
          mkdir -p $REPORTS_DIR/sonarcloud
          curl -s -u ${{ secrets.SONAR_TOKEN }}: \
            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=jdpatilonline_DevSecOps_GitAction" \
            | jq '.' > $REPORTS_DIR/sonarcloud/sonarcloud-report.json
            ls -alR $REPORTS_DIR
            cat $REPORTS_DIR/sonarcloud/sonarcloud-report.json

      # Upload the summary file as artifact
      - name: Upload SonarCloud Analysis with Quality Gate
        uses: actions/upload-artifact@v4
        with:
          name: SonarCloud Analysis with Quality Gate
          path: sonarcloud-quality-gate.json
          
      # ---- Export SonarCloud Report ----
      - name: Export SonarCloud Report
        run: |
          mkdir -p $REPORTS_DIR/sonarcloud
          #curl -s -u $SONAR_TOKEN: \
          #  "https://sonarcloud.io/api/issues/search?componentKeys=jdpatilonline_DevSecOps_GitAction&types=VULNERABILITY,BUG&resolved=false&ps=500" \
          #  -o $REPORTS_DIR/sonarcloud/sonarcloud-report.json
          ls -alR $REPORTS_DIR

      # ---- Network Scan - Nmap ----
      - name: Nmap Scan
        run: |
          mkdir -p $REPORTS_DIR/nmap
          HOST=$(echo "$TARGET_URL" | sed 's~http[s]*://~~')
          docker run --rm -v $(pwd)/$REPORTS_DIR/nmap:/data uzyexe/nmap -Pn -p 80,443 -v -sV -A -oX /data/nmap.xml $HOST
          ls -alR $REPORTS_DIR

      # ---- Network Scan - Nikto ----
      - name: Nikto Scan
        run: |
          mkdir -p $REPORTS_DIR/nikto
          HOST=$(echo "$TARGET_URL" | sed 's~http[s]*://~~')
          docker run --rm -u 0 -v $(pwd)/$REPORTS_DIR/nikto:/report secfigo/nikto -h $HOST -Tuning 123b -output /report/nikto-output.xml || true
          ls -alR $REPORTS_DIR

      # ---- DAST - ZAP Scan ----
      - name: OWASP ZAP Scan
        run: |
          mkdir -p $REPORTS_DIR/zap
          chmod -R 777 $REPORTS_DIR/zap
          docker run --rm -v $(pwd)/$REPORTS_DIR/zap:/zap/wrk zaproxy/zap-stable zap-baseline.py -t $TARGET_URL -m 120 -j -d -x zap_report.xml -r zap_report.html || true
          ls -alR $REPORTS_DIR

      # ---- Upload reports ----
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: DevSecOps-Reports
          path: ${{ env.REPORTS_DIR }}

  # ---------- DEFECTDOJO ----------
  defectdojo_upload:
    runs-on: ubuntu-latest
    needs: security_scans
    if: always()
    env:
      DEFECTDOJO_TOKEN: ${{ secrets.DEFECTDOJO_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Reports
        uses: actions/download-artifact@v4
        with:
          name: DevSecOps-Reports
          path: ${{ env.REPORTS_DIR }}

      - name: Upload Reports to DefectDojo
        run: |
          set -x
          REPORT_DIR="${{ env.REPORTS_DIR }}"

          declare -A REPORTS
          REPORTS["trufflehog/trufflehog.json"]="Trufflehog Scan"
          REPORTS["GitGuardian/ggshield-report.json"]="GitGuardian Scan"
          REPORTS["trivy/trivy-fs-report.json"]="Trivy Scan"
          REPORTS["semgrep/semgrep-report.json"]="Semgrep JSON Report"
          REPORTS["Snyk/snyk-sca.json"]="Snyk Scan"
          REPORTS["sonarcloud/sonarcloud-report.json"]="SonarQube Scan"
          REPORTS["nmap/nmap.xml"]="Nmap Scan"
          REPORTS["nikto/nikto-output.xml"]="Nikto Scan"
          REPORTS["zap/zap_report.xml"]="ZAP Scan"

          for REL_PATH in "${!REPORTS[@]}"; do
            FULL_PATH="$REPORT_DIR/$REL_PATH"
            SCAN_TYPE="${REPORTS[$REL_PATH]}"

            if [ -f "$FULL_PATH" ]; then
              echo "Uploading $SCAN_TYPE -> $FULL_PATH"
              curl -X POST "${{ env.DEFECTDOJO_URL }}" \
                -H "Authorization: Token $DEFECTDOJO_TOKEN" \
                -F "engagement_name=${{ env.ENGAGEMENT_NAME }}" \
                -F "file=@$FULL_PATH" \
                -F "scan_type=$SCAN_TYPE" \
                -F "product_type_name=${{ env.PRODUCT_TYPE_NAME }}" \
                -F "product_name=${{ env.PRODUCT_NAME }}"
              echo "Successfully uploaded: $SCAN_TYPE"
            else
              echo "WARNING: File not found, skipping: $FULL_PATH"
            fi
          done
