name: Dastardly Scan

on:
  workflow_dispatch:   # manual trigger, you can add push/PR if needed

permissions:
  contents: read
  security-events: write

jobs:
  dastardly_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Run Dastardly scan directly using the public image
      - name: Run Dastardly Scan
        run: |
          docker run --rm --user root \
            -e BURP_START_URL=http://altoro.testfire.net/ \
            -e BURP_REPORT_FILE_PATH=/github/workspace/dastardly-report.xml \
            -v ${{ github.workspace }}:/github/workspace \
            public.ecr.aws/portswigger/dastardly:latest || true
            ls -al

      # Show report in logs
      - name: Print Dastardly Report
        run: cat dastardly-report.xml

      # Upload the report as an artifact
      - name: Upload Dastardly Report
        uses: actions/upload-artifact@v4
        with:
          name: dastardly-report
          path: dastardly-report.xml
