
name: GitGuardian scan

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  scanning:
    runs-on: ubuntu-latest
    name: GitGuardian scan

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for full repo scan

      - name: Install ggshield
        run: pip install ggshield

      - name: GitGuardian Full Repo Scan (JSON Output)
        run: ggshield secret scan repo --all --show-secrets --format json --output ggshield-report.json .
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

      - name: Upload JSON Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ggshield-json-report
          path: ggshield-report.json
