
name: GitGuardian scan

on:
 # push:
 # pull_request:
  workflow_dispatch:

jobs:
  scanning:
    runs-on: ubuntu-latest
    name: GitGuardian scan

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for full repo scan

      - name: GitGuardian Full Repo Scan (JSON Output)
        run: |
          pip install --upgrade ggshield
          ggshield api-status
          ggshield secret scan ci --json > ggshield-report.json || true
          ggshield secret scan ci --exit-zero-on=low,medium
          # ggshield secret scan path Test.txt --show-secrets --format json --output ggshield-report.json || true # scan path
          # ggshield secret scan repo --show-secrets --format json --output ggshield-report.json . # scan repo
          ls -al
          echo "Print the result output"
          cat ggshield-report.json || true
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

      - name: Upload JSON Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ggshield-json-report
          path: ggshield-report.json
