

name: ZAP Baseline Scan

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ZAP Baseline Scan
        id: zap
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://testphp.vulnweb.com'
          cmd_options: '-a'     # Include active checks
          format: 'html'        # Generate HTML report
          report_file_name: 'zap-report.html'

      # Upload HTML Report
      - name: Upload HTML Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-html-report
          path: zap-report.html
