name: ZAP Baseline Scan

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write
  security-events: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://testphp.vulnweb.com'
          cmd_options: '-a'
          format: 'html'
          report_file_name: 'zap-report.html'

      # List files in the workspace to confirm report exists
      - name: List files
        run: ls -l

      # Print the ZAP report to the workflow logs
      - name: Show ZAP Report
        run: cat zap-report.html

        with:
          name: zap-report
          path: zap-report.html
