name: Snyk Project File Scan

on:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  snyk_file_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install the Snyk CLI
      - name: Set up Snyk CLI
        uses: snyk/actions/setup@master
        with:
          snyk-version: latest

      # Run Snyk scan directly on project files (no build)
      - name: Run Snyk Scan
        run: |
          ls docs/
          cd docs/
          npm install
          #snyk test --all-projects --severity-threshold=low --json-file-output=snyk-report.json
          #snyk test --all-projects --severity-threshold=medium --json-file-output=snyk-report.json
          #snyk code test --all-projects --severity-threshold=medium --json-file-output=snyk-report.json # To Perform SAST scan
          snyk test --all-projects --severity-threshold=high --json-file-output=snyk-report.json # To perform SCA Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # use to upload the result to synk dashboard portal
      - name: Monitor Project in Snyk
        run: snyk monitor --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


      # Upload the report
      - name: Upload Snyk Report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.json
